apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment #name of the deployment
spec: #configurer the deployment
  replicas: 1 #hove many pods
  selector: #select the pods to manage by the deployment controller
    matchLabels: #match the labels
      app: portfolio-react #label
      app: server #label
  template:
    metadata:
      labels:
        app: portfolio-react #label
        group: server #label
    spec:
      containers: #specify the containers
        - name: server
          imagePullPolicy: Always
          image: maksymposkannyi/portfolio-react-prod-server:latest
          livenessProbe: # check the health of the pod
            httpGet:
              path: /api/works
              port: 80
            initialDelaySeconds: 3 #delay before the probe starts
            periodSeconds: 3 #how often to perform the probe
            timeoutSeconds: 1 #when the probe times out
            successThreshold: 1 #how many times the probe must be successful
            failureThreshold: 3 #how many times the probe must fail
