name: Portfolio React CI
on:
  push:
      branches: [main]
    pull_request:
      branches: [main]
jobs:
  build:
    runs-on: widows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version '20'
        use: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build --prefix client